# This rule is not used by the project sampleweb itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to stable.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sampleweb
    app.kubernetes.io/managed-by: kustomize
  name: firstcrd-viewer-role
rules:
- apiGroups:
  - stable.example.com
  resources:
  - firstcrds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stable.example.com
  resources:
  - firstcrds/status
  verbs:
  - get
