# This rule is not used by the project sampleweb itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over stable.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sampleweb
    app.kubernetes.io/managed-by: kustomize
  name: firstcrd-admin-role
rules:
- apiGroups:
  - stable.example.com
  resources:
  - firstcrds
  verbs:
  - '*'
- apiGroups:
  - stable.example.com
  resources:
  - firstcrds/status
  verbs:
  - get
