---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.example.com
  resources:
  - firstcrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.example.com
  resources:
  - firstcrds/finalizers
  verbs:
  - update
- apiGroups:
  - stable.example.com
  resources:
  - firstcrds/status
  verbs:
  - get
  - patch
  - update
